// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB05N1mVNT5TaFVrwXTTENc7LfaxheypTg',
    appId: '1:411417923508:web:ed006b83855a6faaa32ce1',
    messagingSenderId: '411417923508',
    projectId: 'quicksafe-10044',
    authDomain: 'quicksafe-10044.firebaseapp.com',
    storageBucket: 'quicksafe-10044.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLlU0t-z-4JUvrqxVU4x2TOsyZYbTn--8',
    appId: '1:411417923508:android:b3dc4101b79e8369a32ce1',
    messagingSenderId: '411417923508',
    projectId: 'quicksafe-10044',
    storageBucket: 'quicksafe-10044.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgGjGSZONph639VLadq0UCBAwFknrdHWg',
    appId: '1:411417923508:ios:5c364f3973e1ec87a32ce1',
    messagingSenderId: '411417923508',
    projectId: 'quicksafe-10044',
    storageBucket: 'quicksafe-10044.appspot.com',
    androidClientId: '411417923508-f25t6au0q5cjjamt3uanb9fv52jspugk.apps.googleusercontent.com',
    iosClientId: '411417923508-kj3hgqr0ot901uv0b0hl22f5ti2jtlhe.apps.googleusercontent.com',
    iosBundleId: 'com.example.quicksafeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgGjGSZONph639VLadq0UCBAwFknrdHWg',
    appId: '1:411417923508:ios:5c364f3973e1ec87a32ce1',
    messagingSenderId: '411417923508',
    projectId: 'quicksafe-10044',
    storageBucket: 'quicksafe-10044.appspot.com',
    androidClientId: '411417923508-f25t6au0q5cjjamt3uanb9fv52jspugk.apps.googleusercontent.com',
    iosClientId: '411417923508-kj3hgqr0ot901uv0b0hl22f5ti2jtlhe.apps.googleusercontent.com',
    iosBundleId: 'com.example.quicksafeProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB05N1mVNT5TaFVrwXTTENc7LfaxheypTg',
    appId: '1:411417923508:web:582ae218b08926aba32ce1',
    messagingSenderId: '411417923508',
    projectId: 'quicksafe-10044',
    authDomain: 'quicksafe-10044.firebaseapp.com',
    storageBucket: 'quicksafe-10044.appspot.com',
  );

}